Wdp210501 21 - Add stars functionality.
odevpl/wdp-2105-01 pull request #19
Opened 2021-05-15 16:06 UTC by skwiryt

2021-05-17 09:43 UTC, odevpl requested changes
2 komentarze + na Twoim branchu pojawiają się błędy związane z customStars. Zerknij w konsolę

2021-05-17 09:43 UTC, odevpl commented on src/components/layout/TopBar/TopBar.js
> +                <FontAwesomeIcon className={styles.icon} icon={faUser} />{' '}
A co tu robi to {' '} ?

2021-05-17 09:43 UTC, odevpl commented on src/components/layout/TopBar/TopBar.js
> +                <FontAwesomeIcon className={styles.icon} icon={faLock} />{' '}
jak wyżej

2021-05-17 10:21 UTC, skwiryt commented on src/components/layout/TopBar/TopBar.js
> +                <FontAwesomeIcon className={styles.icon} icon={faLock} />{' '}
Stary numer. Czy ja mam tu jakiś automat, który to wstawia? Cierpliwości, dojdę do tego.

2021-05-18 06:56 UTC, odevpl commented on src/components/layout/TopBar/TopBar.js
> +                <FontAwesomeIcon className={styles.icon} icon={faLock} />{' '}
Nie wiem co masz na komputerze :D A dasz radę to skasować? :)

2021-05-18 07:43 UTC, skwiryt commented
Poprawione, mam nadzieję.

2021-05-18 11:35 UTC, skwiryt commented
Patryk, widzę to z powrotem na Kanbanie, TopBar jest poprawiony, co tu poszło nie tak?

2021-05-18 14:40 UTC, skwiryt commented on src/components/layout/TopBar/TopBar.js
> +                <FontAwesomeIcon className={styles.icon} icon={faLock} />{' '}
Poprawione.

2021-05-20 05:55 UTC, merged