Wdp210501 39
odevpl/wdp-2105-01 pull request #34
Opened 2021-05-19 13:36 UTC by KatarzynaStrumidlo

2021-05-20 10:58 UTC, KatarzynaStrumidlo reviewed
Klikanie w guzik nie do końca działa jak powinno. React twierdzi, że stan openBot jest true już przy włączeniu strony, więc wyświetla się chat zamiast przycisku.

2021-05-21 09:16 UTC, odevpl requested changes

2021-05-21 09:16 UTC, odevpl commented on src/components/layout/Header/Header.js
> +    <div className={styles.chatbot}>
Hej! A nie można by było tego diva wrzucić bezpośrednio do klasy Chatbot?

2021-05-21 09:16 UTC, odevpl commented on src/components/views/Homepage/Homepage.js
> +//import Chatbot from '../../features/Chatbot/Chatbot';
Niepotrzebne, to do kosza.
Nie śmiecimy :)

2021-05-21 13:12 UTC, KatarzynaStrumidlo commented on src/components/layout/Header/Header.js
> +    <div className={styles.chatbot}>
Hej! W sumie można. Przerzucony ;)

2021-05-21 13:12 UTC, KatarzynaStrumidlo commented on src/components/views/Homepage/Homepage.js
> +//import Chatbot from '../../features/Chatbot/Chatbot';
Usunięte :)

2021-05-23 08:56 UTC, odevpl approved these changes

2021-05-23 08:56 UTC, merged