Add carousel to Brand Component - task 31
odevpl/wdp-2105-01 pull request #36
Opened 2021-05-19 19:33 UTC by BarbaraPakula

task: Należy dodać funkcjonalność to animacji slidera z markami, tak aby strzałki przesuwały slider o tyle elementów, ile jest widoczne przy danej szerokości ekranu (np. w wersji desktop jest ich 6).

Rozwiązanie: Dodałam funkcjonalność z markerami oraz swipe), Do poprawy Css i RWD. Zadanie pokrywa się z 32 więc tu przekażę dalej instrukcje jak przejdzie pull. 

-wymagana była instalacja: npm install --save react-elastic-carousel
-Ostylowanie na razie wrzucone do global bo tylko wtedy mi działało. Zastanawiam się czy da się uniknąć wpisywania tego w zmiennych globalnych?

2021-05-19 19:46 UTC, Robert-szy commented on src/styles/global.scss
> +    background-color: $darkGray !important;
Czy zostawiamy jednak zmienną w kolorze głównym czy nadajemy kolory jako zmienne komponentowe? Trzeba wtedy dodać by było jakiś kolor w settings.css jeszcze. To samo w linii 28.

2021-05-19 19:48 UTC, Robert-szy commented on src/styles/global.scss
> +  background-color: black;
Mieliśmy definiować kolory za pomocą zmiennych? (l. 16 i 17)

2021-05-19 19:51 UTC, Robert-szy requested changes
Uwagi tylko do nazewnictwa kolorów i zmiennych kolorów

2021-05-19 20:02 UTC, BarbaraPakula commented on src/styles/global.scss
> +    background-color: $darkGray !important;
Brakowało mi koloru więc strzeliłam najciemniejszy z palety na razie dla przykładu. Kolorów jeszcze nie ogarnęłam. Zastanawiam się czy da się to wyrzucić poza global.

2021-05-19 20:03 UTC, BarbaraPakula commented on src/styles/global.scss
> +  background-color: black;
Masz rację. Chcę najciemniejszy z palety. Poprawię jak ustalimy jaki to ma być kolor.

2021-05-20 23:07 UTC, Robert-szy commented on src/styles/global.scss
> +  background-color: black;
Zmienna? :)

2021-05-20 23:08 UTC, Robert-szy commented on src/styles/global.scss
> +  color: white;
Zmienna? :)

2021-05-20 23:12 UTC, Robert-szy reviewed
Zastanawiam się jaki powinien być przy takim review stopień "upierdliwości" sprawdzającego. :) Będąc w roli PM na pewno spory - "klient tak chce i koniec" ale w każdej innej sytuacji można na przykład przymknąć na coś oko czy nie? Coś mało ważnego oczywiście, nie jakieś poważne rzeczy.

2021-05-21 08:41 UTC, BarbaraPakula commented on src/styles/global.scss
> +  color: white;
Poprawione

2021-05-21 08:48 UTC, Robert-szy reviewed
Ok, :)

2021-05-21 08:51 UTC, Robert-szy approved these changes

2021-05-21 09:18 UTC, merged