Add BlogHomepage to Homepage
odevpl/wdp-2105-01 pull request #40
Opened 2021-05-20 10:52 UTC by KatarzynaStrumidlo

2021-05-20 12:12 UTC, justinaz90 commented on src/components/features/BlogHomepage/BlogHomepage.module.scss
> +      font-weight: light;
Myślę, że chodziło tutaj o wartość "lighter"? ;) Wydaje mi się, że jeśli dla elementów date i comments  damy nieco jaśniejszą czcionkę, oddalimy od bocznych krawędzi oraz zwiększymy bottom padding to będzie to bardziej zbliżone do koncepcji z wizualizacji :)

2021-05-20 12:14 UTC, justinaz90 commented on src/components/views/Homepage/Homepage.js
> +    <BlogHomepage />
Drobna zmiana do wdrożenia:
AC: "2. Komponent ma się znajdować nad sekcją Brands."

2021-05-20 12:16 UTC, justinaz90 requested changes
Komponent prezentuje się na prawdę dobrze, dodałam 2 uwagi do zmiany/rozważenia

2021-05-21 08:56 UTC, KatarzynaStrumidlo commented on src/components/features/BlogHomepage/BlogHomepage.module.scss
> +      font-weight: light;
Oki, poprawione :)

2021-05-21 11:30 UTC, justinaz90 commented on src/components/views/Homepage/Homepage.js
>      <BlogHomepage />
Jeszcze jeden poziom wyżej ;) NAD brands
Reszta wygląda elegancko 👍

2021-05-21 12:51 UTC, Akagi80 requested changes
Świetna robota!
Tak jak Justyna napisała zostało przeniesienie bloga nad Brands i konflikt.
Ps. Dziwnie zaczytała się ikonka kalendarza (tylko u mnie?), może wersja  faCalendarAlt była by bliższa tej z wizualizacji?

2021-05-21 13:03 UTC, KatarzynaStrumidlo commented on src/components/views/Homepage/Homepage.js
>      <BlogHomepage />
Przeniesione ;)

2021-05-21 13:40 UTC, KatarzynaStrumidlo commented
Przeniosłam nad Brands i zmieniłam ikonkę kalendarza (rzeczywiście lepiej wygląda). Dzięki :)

2021-05-21 16:05 UTC, justinaz90 commented
Wygląda świetnie! :)

2021-05-21 16:33 UTC, Akagi80 approved these changes

2021-05-23 09:52 UTC, merged