Fix bug: white stripe in mobile mode
odevpl/wdp-2105-01 pull request #43
Opened 2021-05-20 20:30 UTC by skwiryt

The problem was in Brands (I added scaling of pictures) and in ProductSearch (switched off col-auto for small sceens). Both components do not look fine in mobile mode. I needs to be solved by RWD tickets. I did not consider it as part of this one.

2021-05-20 21:22 UTC, Robert-szy commented on src/components/features/Brands/Brands.module.scss
> +      img {
Proporcje? Patrz komentarz główny

2021-05-20 21:26 UTC, BarbaraPakula requested changes
It is better than it was, but we still have white space and cuts off the amount of products in the cart. The customer requires that the cart can contain a five-digit number of products. See the CompanyClaim component. Now the problem is there.

2021-05-20 21:28 UTC, Robert-szy reviewed
Lepiej się wszystko skaluje ale:
1. Menu: 
- zgubiło się stylowanie menu. brakuje domyślnego podświetlenia w kolorze main plus ciemna kreska powyżej, które powinny zajmować wysokość całego menuBara (patrz design). Tyle że jak porównuję z masterem to w masterze też już nie ma tego stylowania, musiało chyba gdzieś wcześniej wypaść. Przy dodawaniu podstron?
- na szerokościach mobilnych, na ubuntu + FF ikona wyszukiwania wyświetla się poza polem wyszukiwania. rozlatuje się to
- ogólnie chyba powinien być osobny taks dla samego RWD wyszukiwania, bo chociaż skaluje się lepiej to chyba nadal słabo wygląda na mobile. Wyobrażam to sobie na przykład tak, że pola kategorii i wyszukiwania układają się kolumnowo albo że kasujemy opis "search products" i zostawiamy samą ikonę w tym polu. 
2. Brands 
- obrazki w pasku się skalują tylko że po przeskalowaniu są nieczytelne. 
- nie wiem czy skalowanie nie powinno zachowywać proporcji.  #obraazki byłyby małe ale przynajmniej proporcjonalne
Nie wiem czy nie lepiej było to zostawić aż dojdzie task funkcji i RWD, w którym w zależności od szerokości zmienia się liczą wyświetlanych ikon.

2021-05-21 05:31 UTC, skwiryt commented
Robert - nie widzę teraz, o jaki komentarz główny chodzi. Przepraszam za ten angielski, coś mi się po..., Barbara, ze wszystkimi Twoimi uwagami się zgadzam, w moim rozumieniu ten bug miał tylko załatwić ten pasek, co starałem się zrobić nie psując aktualnego mastera, zaś nie chcę wchodzić w rozwiązania, które powinny być załatwione przez inne tickety. Albo te tickety już są, albo powinien je PM wystawić. Przecież nie chcemy, żeby za jeden punkt PM chciał, żebyśmy rozwiązali RWD wszystkiego :-). Oczywiście to, co zrobiłem, pewnie da się zrobić lepiej lub inaczej, dawajcie.

2021-05-21 06:54 UTC, Robert-szy commented
Hejka – ogólnie napisałem w komentarzu do całego CR, nie w komentarzach do poszczególnych fragmentów.


From: skwiryt ***@***.***>
Sent: Friday, May 21, 2021 7:31 AM
To: odevpl/wdp-2105-01 ***@***.***>
Cc: Robert-szy ***@***.***>; Comment ***@***.***>
Subject: Re: [odevpl/wdp-2105-01] Fix bug: white stripe in mobile mode (#43)


Robert - nie widzę teraz, o jaki komentarz główny chodzi. Przepraszam za ten angielski, coś mi się po..., Barbara, ze wszystkimi Twoimi uwagami się zgadzam, w moim rozumieniu ten bug miał tylko załatwić ten pasek, co starałem się zrobić nie psując aktualnego mastera, zaś nie chcę wchodzić w rozwiązania, które powinny być załatwione przez inne tickety. Albo te tickety już są, albo powinien je PM wystawić. Przecież nie chcemy, żeby za jeden punkt PM chciał, żebyśmy rozwiązali RWD wszystkiego :-). Oczywiście to, co zrobiłem, pewnie da się zrobić lepiej lub inaczej, dawajcie.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/odevpl/wdp-2105-01/pull/43#issuecomment-845664958>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ASKPDPVLHS4VSLFE675ZUPLTOXV2HANCNFSM45H2IKQQ>.

2021-05-21 07:04 UTC, skwiryt commented
Tak, Robert Tak, zorientowałem się i przeedytowałem odpowiedź, sorry.

2021-05-21 07:26 UTC, skwiryt commented
Barbara, jeszcze może bardziej szczegółowo. Zwróć uwagę, że te cyferki wylatywały na biały pasek, już w masterze. Pasek był do zlikwidowania w bugu, więc ucięło literki. Wiele komponentów rozwala się na różne sposoby w mobile. Ich opracowanie albo poprawa, chyba powinny być w innych ticketach. No chyba, że RWD tego komponentu było już żądane w jakimś tickecie, działało w masterze, a mój kod to psuje. Może to przeoczyłem, nie mogę znaleźć.

2021-05-21 07:46 UTC, BarbaraPakula reviewed
Wystarczy przesunąć na mobile cartCounter lekko w lewo i diva z ikoną koszyka (w CompanyClaim. I wtedy biały pasek zniknie.

2021-05-21 07:55 UTC, BarbaraPakula commented
Tylko zerknij na mobile i przesuń ekran w lewo.  Pasek nie zniknął. I tylko o  to chodzi aby go nie było
[cid:e2d64b8f-105a-4c47-b2d8-3518c69276a1]

________________________________
Od: skwiryt ***@***.***>
Wysłane: piątek, 21 maja 2021 09:26
Do: odevpl/wdp-2105-01 ***@***.***>
DW: Barbara ***@***.***>; Comment ***@***.***>
Temat: Re: [odevpl/wdp-2105-01] Fix bug: white stripe in mobile mode (#43)


Barbara, jeszcze może bardziej szczegółowo. Zwróć uwagę, że te cyferki wylatywały na biały pasek, już w masterze. Pasek był do zlikwidowania w bugu, więc ucięło literki. Wiele komponentów rozwala się na różne sposoby w mobile. Ich opracowanie albo poprawa, chyba powinny być w innych ticketach. No chyba, że RWD tego komponentu było już żądane w jakimś tickecie, działało w masterze, a mój kod to psuje. Może to przeoczyłem, nie mogę znaleźć.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/odevpl/wdp-2105-01/pull/43#issuecomment-845725214>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AR7T7MPMQI7NC2XJFYOGIQTTOYDKHANCNFSM45H2IKQQ>.

2021-05-21 07:59 UTC, skwiryt commented
Barbara, ok, ok. Uczymy się. Celowo tego nie zrobiłem, ponieważ w większości przypadków "wystarczy tylko". Bardzo ciężko usuwać bug, po bugu, jeśli warunkiem uznania jednego buga ma być usuwanie innych. Może to źle rozumiem. Przed moim kodem, ten problem istniał? Tak. Czy ticket tego dotyczył? - nie. Więc tego nie dotknąłem. Choćby dlatego, że być może PM właśnie wystawił na to inny ticket i ktoś to robi. Niech nas Patryk z tego przeszkoli. Samo poprawienie, oczywiście nie jest problemem, dzięki, dzięki. Nawiasem, czym więcej "wydębimy" ticektów od PM-a, tym lepiej dla nas. Teamwork :-)

2021-05-21 08:06 UTC, BarbaraPakula commented
Jasne. Jeśli zlikwidujesz pasek to będzie ok. Jak poucina literki to je poprawimy. Task miał usunąć pasek a on tam jest.


Pozdrawiam
Barbara Pakuła
+48 884805835

________________________________
Od: skwiryt ***@***.***>
Wysłane: piątek, 21 maja 2021 10:00
Do: odevpl/wdp-2105-01 ***@***.***>
DW: Barbara ***@***.***>; Comment ***@***.***>
Temat: Re: [odevpl/wdp-2105-01] Fix bug: white stripe in mobile mode (#43)


Barbara, ok, ok. Uczymy się. Celowo tego nie zrobiłem, ponieważ w większości przypadków "wystarczy tylko". Bardzo ciężko usuwać bug, po bugu, jeśli warunkiem uznania jednego buga ma być usuwanie innych. Może to źle rozumiem. Przed moim kodem, ten problem istniał? Tak. Czy ticket tego dotyczył? - nie. Więc tego nie dotknąłem. Choćby dlatego, że być może PM właśnie wystawił na to inny ticket i ktoś to robi. Niech nas Patryk z tego przeszkoli. Samo poprawienie, oczywiście nie jest problemem, dzięki, dzięki. Nawiasem, czym więcej "wydębimy" ticektów od PM-a, tym lepiej dla nas. Teamwork :-)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/odevpl/wdp-2105-01/pull/43#issuecomment-845744360>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AR7T7MOON46XJKFYE3JX43LTOYHIXANCNFSM45H2IKQQ>.

2021-05-21 08:23 UTC, Robert-szy commented
Pewnie że tak, masz rację. Tylko poprawiając pasek „dotknąłeś” przy okazji menu czy brandów a ja na przykład nie do końca wiedząc ze miałeś się zająć tylko biały paskiem napisałem że rozsypało się coś w brandach i w menu 😊

From: skwiryt ***@***.***>
Sent: Friday, May 21, 2021 10:00 AM
To: odevpl/wdp-2105-01 ***@***.***>
Cc: Robert-szy ***@***.***>; Comment ***@***.***>
Subject: Re: [odevpl/wdp-2105-01] Fix bug: white stripe in mobile mode (#43)


Barbara, ok, ok. Uczymy się. Celowo tego nie zrobiłem, ponieważ w większości przypadków "wystarczy tylko". Bardzo ciężko usuwać bug, po bugu, jeśli warunkiem uznania jednego buga ma być usuwanie innych. Może to źle rozumiem. Przed moim kodem, ten problem istniał? Tak. Czy ticket tego dotyczył? - nie. Więc tego nie dotknąłem. Choćby dlatego, że być może PM właśnie wystawił na to inny ticket i ktoś to robi. Niech nas Patryk z tego przeszkoli. Samo poprawienie, oczywiście nie jest problemem, dzięki, dzięki. Nawiasem, czym więcej "wydębimy" ticektów od PM-a, tym lepiej dla nas. Teamwork :-)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/odevpl/wdp-2105-01/pull/43#issuecomment-845744360>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ASKPDPTBEPNAZ4QW57Y4GTLTOYHIXANCNFSM45H2IKQQ>.

2021-05-21 08:24 UTC, skwiryt commented
Barbara, chcesz powiedzieć, że na Twoim ekranie, dalej jest pasek? Kurczę, u mnie nie ma, poza scrollbarem, którym się nie zajmujemy, chyba. Potwierdź, to pstryknę zdjęcie.

2021-05-21 08:31 UTC, Robert-szy commented
To pewnie to samo, co poprzednio było z samym menu – na W10 było ok, na Ubuntu źle. Tu może być odwrotnie.
Ale przy okazji mam dwie ważne spawy – czy Git i komentarze to dobre miejsce na takie dyskusje? Jak to się robi? Nie powinniśmy tej narady robić w innym miejscu? Przenieść na forum? Na razie to taki poligon więc chyba spoko ale jak to w normalnych warunkach jest? Patryk?
I druga sprawa – już niech będzie tutaj  – może trzeba pomyśleć o takim spisie bugów. Zróbmy gdzieś jakąś listę gdzie każdy wpisze co akurat zauważył, co się popsuło, jak wprowadził swoje zmiany itp. Tak żeby każdy miał dostęp, a PM będzie mógł sobie zdecydować co z tego wrzuca na listę projektu do poprawy? Albo jakiś wątek na forum?

From: skwiryt ***@***.***>
Sent: Friday, May 21, 2021 10:25 AM
To: odevpl/wdp-2105-01 ***@***.***>
Cc: Robert-szy ***@***.***>; Comment ***@***.***>
Subject: Re: [odevpl/wdp-2105-01] Fix bug: white stripe in mobile mode (#43)


Barbara, chcesz powiedzieć, że na Twoim ekranie, dalej jest pasek? Kurczę, u mnie nie ma, poza scrollbarem, którym się nie zajmujemy, chyba. Potwierdź, to pstryknę zdjęcie.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/odevpl/wdp-2105-01/pull/43#issuecomment-845770139>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ASKPDPRGNC7KSCEZ664OKTTTOYKGRANCNFSM45H2IKQQ>.

2021-05-21 08:41 UTC, skwiryt commented
Myślę, że wyjaśnieniem, tego paska, to lepiej tutaj się zająć. Spis wszystkich bugów, można zapodać, chyba, na czacie, ja myślę, że to dobry pomysł jest. Jak rozumieć zakres buga, to właściwie sobie wydyskutowaliśmy, jak mi to PM puści, to może należy rozumieć, że mamy rację. Barbara, jesteś w Windows, czy w Linux?

2021-05-21 09:12 UTC, odevpl commented
Wrzuciłem dyskusję na chat, by nie spamować Wam skrzynek :)

2021-05-21 15:48 UTC, skwiryt commented
Odtworzyłem ten pasek, ale symulacja mobile jest niefajna u mnie. Po zmianach wprowadzonych przez Barbarę karuzelą w Brands i skalowaniem obrazków, oczywiście moje skalowanie nie jest potrzebne i w mergu je usunąłem.

2021-05-21 19:49 UTC, BarbaraPakula requested changes

2021-05-21 19:49 UTC, BarbaraPakula commented on src/components/layout/CompanyClaim/CompanyClaim.module.scss
> +      margin-right: 25px;
pomiędzy  .cart {   a   .cartBox {
dodaj:
   @include mobile {
      padding-right: 40px;
     }

.... i biała zmora zniknie;-) przynajmniej na chwilę

2021-05-21 20:26 UTC, skwiryt commented
Hej, Nie ma sprawy, jeśli idzie o wprowadzenie zmian. Mam tu inny problem, jeśli ten pasek tam ciągle jest, to muszę znaleźć jakiś sposób na testowanie tego mobile. Bo to wygląda tak u mnie to wygląda.

2021-05-21 20:27 UTC, skwiryt commented
![image](https://user-images.githubusercontent.com/22455210/119194659-b3812700-ba83-11eb-8c00-712358b4b017.png)

2021-05-21 20:31 UTC, skwiryt commented
Krótko mówiąc, skoro mówisz, że dalej jest to widoczne na Windows, oznacza, że muszę nad tym tak długo siedzieć, aż znajdę sposób na odtworzenie tego paska u siebie. Inaczej, będę działał po omacku.

2021-05-22 07:30 UTC, BarbaraPakula approved these changes

2021-05-23 00:53 UTC, Robert-szy approved these changes

2021-05-23 09:57 UTC, merged