Add to CompareBox Product name, price, old price and favouriets
odevpl/wdp-2105-01 pull request #45
Opened 2021-05-21 14:26 UTC by BarbaraPakula

Zadanie: Twoim zadaniem jest dodanie nazwy produktu, cen, statusu bycia ulubionymi pod wybranymi produktami w sekcji compare.

2021-05-22 18:22 UTC, Akagi80 commented on src/components/features/CompareBox/CompareBox.js
> +              </p>
moja propozycja do rozważenia :)
<p className={styles.price_old}>
  {product.oldPrice ? <p>Old price: <span> $ {product.oldPrice} </span> </p> : ''}
</p>

2021-05-22 18:22 UTC, Akagi80 requested changes
Ponownie dobra robota!
Może warto tak jak w przypadku serduszka "faHeart", które pojawia się tylko w przypadku gdy produkt jest oznaczony, nie wyświetlać informacji "Old price (...)" ?

2021-05-22 18:49 UTC, Akagi80 commented on src/components/features/CompareBox/CompareBox.js
> +const CompareBox = ({ getCompared, removeItem, handleFavoriteClick }) => {
handleFavoriteClick - VSC mi krzyczy, że nie używamy tego w kodzie poniżej  :)

2021-05-23 10:14 UTC, BarbaraPakula commented on src/components/features/CompareBox/CompareBox.js
> +const CompareBox = ({ getCompared, removeItem, handleFavoriteClick }) => {
No jasne! Poprawiam

2021-05-23 10:15 UTC, BarbaraPakula commented
> Ponownie dobra robota!
> Może warto tak jak w przypadku serduszka "faHeart", które pojawia się tylko w przypadku gdy produkt jest oznaczony, nie wyświetlać informacji "Old price (...)" ?

Dzieje się. Słuszne spostrzeżenie. Poprawiam

2021-05-23 10:19 UTC, BarbaraPakula commented on src/components/features/CompareBox/CompareBox.js
> +              </p>
poprawione :-)

2021-05-23 11:24 UTC, Akagi80 approved these changes

2021-05-23 11:42 UTC, merged