Wdp210501 60
odevpl/wdp-2105-01 pull request #50
Opened 2021-05-23 15:30 UTC by BarbaraPakula

Błąd dotyczy technicznej części funkcjonalności:

W projekcie jest sporo aktywnych przycisków przekierowujących na różne podstrony.
Projekt korzysta z biblioteki React Router, dlatego warto było by to uwzględnić i pozamieniać wszystkie aktywne odsyłacze <a> z linkami z biblioteki routera.

Ticket dotyczy tylko istniejących odsyłaczy/przycisków, które gdzieś kierują.
Ścieżka typu /#/ nie jest tematem ticketu.

2021-05-24 05:33 UTC, odevpl requested changes
Hej!
Co tu robi chatbot?

2021-05-24 13:36 UTC, BarbaraPakula commented
Ciekawe bo w tym pliku poprawiałam tez linki a wyglada jakby cały nowy był.

Pozdrawiam Basia

Wiadomość napisana przez odevpl ***@***.***> w dniu 24.05.2021, o godz. 07:33:

﻿

@odevpl requested changes on this pull request.

Hej!
Co tu robi chatbot?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/odevpl/wdp-2105-01/pull/50#pullrequestreview-666407411>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AR7T7MJMJ6BSBZ5V2BD4GQ3TPHQLRANCNFSM45L2CJ6A>.

2021-05-26 13:12 UTC, Akagi80 requested changes
Założenie zadania zostało spełnione.
Widzę, że podobnie do mnie (WDP210501-57) podpięły Ci się zmiany dotyczące innego brancha.
Wybrnąłem z tego w ten (najbezpieczniejszy) sposób:
1. Pobrałem "świeży" branch master.
 2. Z "mastera" utworzyłem nowy branch (WDP210501 57-v2) 
 3. W nowym branchu naniosłem zmiany wg zadania (skopiowałem je z githuba)
 Nie powinno Ci to zająć więcej niż 5 min i masz problem z głowy :)

2021-05-26 15:51 UTC, BarbaraPakula commented
Tak zrobię. Dzięki

________________________________
Od: Akagi80 ***@***.***>
Wysłane: środa, 26 maja 2021 15:12
Do: odevpl/wdp-2105-01 ***@***.***>
DW: Barbara ***@***.***>; Author ***@***.***>
Temat: Re: [odevpl/wdp-2105-01] Wdp210501 60 (#50)


@Akagi80 requested changes on this pull request.

Założenie zadania zostało spełnione.
Widzę, że podobnie do mnie (WDP210501-57) podpięły Ci się zmiany dotyczące innego brancha.
Wybrnąłem z tego w ten (najbezpieczniejszy) sposób:

  1.  Pobrałem "świeży" branch master.
  2.  Z "mastera" utworzyłem nowy branch (WDP210501 57-v2)
  3.  W nowym branchu naniosłem zmiany wg zadania (skopiowałem je z githuba)
Nie powinno Ci to zająć więcej niż 5 min i masz problem z głowy :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/odevpl/wdp-2105-01/pull/50#pullrequestreview-669000166>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AR7T7MKCMD7UYVUQKB3NII3TPTXU7ANCNFSM45L2CJ6A>.

2021-05-26 16:37 UTC, closed without merging

2021-05-26 16:37 UTC, BarbaraPakula commented
nowy branch --60