Add Blog subpage - Wdp210501 57
odevpl/wdp-2105-01 pull request #51
Opened 2021-05-23 17:44 UTC by Akagi80

Twoim zadaniem jest stworzenie podstrony bloga. Klient chce się wzorować na wizualizacji z załącznika.

AC:
1. Domyślnie na stronie ma się pojawić jeden post z następującymi danymi:
tytuł: Witamy na nowej stronie sklepu!
opis: Lorem ipsum..
zdjęcia: dowolne w proporcjach takich jak na wizualizacji
2. Proporcje powinny być takie, jak na wizualizacji:
9/12 = posty
3/12 = menu z artykułami
3. Menu również powinno być statyczne, dlatego zaproponuj jakieś 4 tytuły i wstaw je do menu
4. Ticket nie dotyczy funkcjonalności oraz RWD

2021-05-23 17:58 UTC, Akagi80 commented
Widzę, że podpięły się commity Basi, którym robiłem CR.... Why?

2021-05-24 05:43 UTC, odevpl requested changes
Pojawił się u Ciebie dziwny kod niezwiązany z zadaniem. Czyżby branch tworzony nie z mastera?

2021-05-24 05:43 UTC, odevpl commented on src/redux/initialState.js
> +      oldPrice: 100,
A co to tu robi?

2021-05-24 05:43 UTC, odevpl commented on src/components/features/CompareBox/CompareBox.module.scss
>  .root {
Czy te zmiany są konieczne?
Chyba nie dotyczą bloga

2021-05-24 05:43 UTC, odevpl commented on src/components/features/CompareBox/CompareBox.js
> +            <div className={styles.description}>
To nie jest blog.

2021-05-24 06:08 UTC, Akagi80 commented
Mój kod znajduje się tylko w commicie "Add Blog subpage" i dotyczył tylko 2 Blog.js oraz Blog.module.scss  
Cała reszta podpięła się po drodze (w międzyczasie robiłem  CR)

2021-05-24 07:46 UTC, closed without merging