Add chatbot - task 39
odevpl/wdp-2105-01 pull request #56
Opened 2021-05-24 11:23 UTC by KatarzynaStrumidlo

2021-05-24 21:02 UTC, Robert-szy commented on src/components/features/Chatbot/Chatbot.js
> +                    src='https://img-premium.flaticon.com/png/512/3421/3421082.png?token=exp=1621430936~hmac=a4b8542f74c140eba120e9ed902e5352'
Nie wczytuje się

2021-05-24 21:04 UTC, Robert-szy commented on src/components/features/Chatbot/Chatbot.js
> +              Need help ? Contact us
Spacja pomiędzy 'help' a znakiem zapytania powoduje że w wyświetlonym przycisku znak zapytania ląduje na początku drugiej linii zamiast na końcu pierwszej :)

2021-05-24 21:14 UTC, Robert-szy requested changes
Cześć. Fajne. :)
Ogólnie warto byłoby chyba poprawić:
- wczytywanie obrazka, nie wczytuje mi się. Ani na Windzie ani na Linuksie
- w kodzie pomiędzy 'help' a znakiem zapytania (napis na przycisku zamkniętego bota) jest spacja. w efekcie na Windzie (Chrome) napis się przełamuje i znak zapytania ląduje na początku drugiej linii zamiast na końcu pierwszej. Wyświetla się za to prawidłowo na Ubuntu i FF.
I takie uwagi wizualne, niekoniecznie istotne i wymagające zmiany ale warto zapytać:
- pole select topic jest szersze od pola konwersacji, czy tak ma być? W wizualizacji są równe.
- no i czy ten dymek (ikona) u dołu ma w 100% odpowiadać wizualizacji, bo też jest nieco inna (podobnie jak ikona wysyłania)

2021-05-26 10:24 UTC, KatarzynaStrumidlo commented on src/components/features/Chatbot/Chatbot.js
> +                    src='https://img-premium.flaticon.com/png/512/3421/3421082.png?token=exp=1621430936~hmac=a4b8542f74c140eba120e9ed902e5352'
ok, zmieniłam na ikonę

2021-05-26 10:24 UTC, KatarzynaStrumidlo commented on src/components/features/Chatbot/Chatbot.js
> +              Need help ? Contact us
spacja usunięta

2021-05-26 10:26 UTC, KatarzynaStrumidlo commented
Dwie pierwsze uwagi uwzględniłam w zmianach, co do uwag wizualnych jeżeli chodzi o wybór tematu to chciałam żeby to w miarę było wyśrodkowane i tekst w środku ładnie wyglądał. A co do ikon to tylko takie znalazłam w wersji darmowej...

2021-05-26 10:28 UTC, Robert-szy approved these changes
Ok

2021-05-26 12:35 UTC, merged