Add RWD to BlogHomepage mobile desktop
odevpl/wdp-2105-01 pull request #75
Opened 2021-05-28 12:25 UTC by BarbaraPakula

Twoim zadaniem jest dodanie RWD do modułu bloga na stronie głównej. Ticket dotyczy wersji mobile i tablet

2021-05-28 13:47 UTC, skwiryt commented
Hej, fajnie. Dostrzegłem jedynie dwie drobne rzeczy. 
Dla rozdzielczości Iphona5 (ok 320px) przycisk Read More się chowa pod obrazkiem.
![image](https://user-images.githubusercontent.com/22455210/119993161-8ecd0800-bfcb-11eb-8e8d-46eeedf8ae52.png)
Oraz dla rozdzielczości jak dla Surface Duo (ok 540px) tytuł się wcina w obrazek i styka się z nim.
![image](https://user-images.githubusercontent.com/22455210/119993468-dbb0de80-bfcb-11eb-81d0-688d663e0b87.png)

2021-05-28 19:53 UTC, skwiryt requested changes
Jak w komentarzu w PR

2021-05-28 23:16 UTC, BarbaraPakula commented
> Jak w komentarzu powyżej.
Poprawione

2021-05-28 23:16 UTC, BarbaraPakula commented
Poprawione :-)

2021-05-30 21:46 UTC, justinaz90 commented on src/components/features/BlogHomepage/BlogHomepage.module.scss
> +      top:70%;
Jeśli dla widoku tablet podniesiemy sekcję "post" nieco wyżej np. na poziom top 60% to zrobi nam się bardziej przejrzysty odstęp pomiędzy postami ;)

2021-05-30 21:47 UTC, justinaz90 requested changes
Super robota!  :) Tylko jedna wskazówka, która wydaje mi się poprawi nieco przejrzystość dla widoku na tablecie

2021-05-30 22:03 UTC, justinaz90 commented on src/components/features/BlogHomepage/BlogHomepage.module.scss
> +$desktop-width: 980px;
Jeszcze jedno - widzę, że dla rozdzielczości 980-991px dzieje się to samo o czym pisał Marek. Jak zmienisz tutaj na $desktop-width: 992px to przycisk Read more nie będzie się chował :)

2021-05-30 22:05 UTC, justinaz90 commented on src/components/features/BlogHomepage/BlogHomepage.module.scss
> +$desktop-width: 980px;
<img width="977" alt="Zrzut ekranu 2021-05-31 o 00 00 50" src="https://user-images.githubusercontent.com/75181606/120121458-e02fef80-c1a3-11eb-9278-268a745b4bd4.png">

2021-05-31 02:55 UTC, BarbaraPakula commented on src/components/features/BlogHomepage/BlogHomepage.module.scss
> +$desktop-width: 980px;
wdrożone 👍 Dzięki za podpowiedzi.

2021-05-31 07:34 UTC, skwiryt commented
Hej, trochę mi brak doświadczenia, prawdopodobnie to jest OK, bo w końcu nie było wizualizacji. Moja wątpliwość dotyczy tego, że przy rozdzielczości ok 550 tj Surface Duo, pomiędzy obrazkami robią się spore dziury. Ale może to można zostawić.

2021-05-31 07:50 UTC, justinaz90 approved these changes

2021-05-31 07:51 UTC, justinaz90 commented
Teraz elegancko ;)

2021-06-01 05:49 UTC, merged