Wdp210501 23 owl
odevpl/wdp-2105-01 pull request #78
Opened 2021-05-28 23:25 UTC by BarbaraPakula

Wymaga instalacji npm: npm install --save owl.carousel or yarn add owl.carousel jquery.

AGAIN

2021-05-30 12:51 UTC, Robert-szy requested changes
zrobiłem drugie podejście, zainstalowałem sobie OWL ale mam błędy w initial state. konfilikty. boję się trochę to ruszać bo to obszerne fragmenty, a nie wiem co do czego. powtarza mi się na przykład klucz "promoted" tylko że w obydwu przypadkach ma kompletnie różną zawartość.  Nic dalej więc nie zrobiłem. Zerknij może o co chodzi bo masz największe pojęcie na pewno

2021-05-30 20:13 UTC, BarbaraPakula commented
> zrobiłem drugie podejście, zainstalowałem sobie OWL ale mam błędy w initial state. konfilikty. boję się trochę to ruszać bo to obszerne fragmenty, a nie wiem co do czego. powtarza mi się na przykład klucz "promoted" tylko że w obydwu przypadkach ma kompletnie różną zawartość. Nic dalej więc nie zrobiłem. Zerknij może o co chodzi bo masz największe pojęcie na pewno

B: rozwiązałam problem w initial state ale i tak coś nie śmiga

2021-05-31 20:11 UTC, Robert-szy requested changes
Działa. Chyba jednak wolałbym tę pierwszą karuzelę :). 
Teraz, co do działania. W kod nie ingeruję bo za dużo tego żeby się szybko rozeznać, jak się nie ma wprawy ale:
- kliknięcie na którąkolwiek z ikon i dołu lewego pudełka z produktem zawiesza aplikację i wyrzuca błędy w konsoli, przynajmniej u mnie, różne handlePopupClick is not a function, handleCompareClick is not a function
- lewa karuzela nie wyświetla starej ceny.  po zrobieniu "obrotu" stara cena natychmiast znika i zostaje tylko opis Old price:
- kompletnie rozleciało się RWD, które było już gotowe i powinno być wcześniej w kodzie. chyba. a jak nie to pewnie są/będzie sporo konfliktów.
Zerknij czy cokolwiek z tego da się jeszcze poprawić (choć czasu już nam się chyba skończył) i czy to wynika ze zmian w karuzeli czy po prostu powinno być zapisane do teoretycznych bugów na przyszłość. Tylko że już chyba nie dla nas :)

2021-05-31 20:15 UTC, Robert-szy commented
Aaaa i zniknęła też ikona QuickView (?), taka z oczkiem

2021-06-01 05:18 UTC, BarbaraPakula commented
Zerknijcie na Wdp 210501 23 v2 #89  tam druga wersja poprawiona o tyle ile się udało ale się nie rozpada ;-)

2021-06-01 05:47 UTC, closed without merging