Wdp210501 45 Add Grid &List View to Store
odevpl/wdp-2105-01 pull request #79
Opened 2021-05-29 18:21 UTC by BarbaraPakula

Brak filtrow poprawnie rozpakowujacych produkty po kategoriach. Widok listy odbiega od oryginalu.

2021-05-30 21:09 UTC, justinaz90 commented on src/components/views/ProductList/ProductList.js
> +                              <div className={styles.grid_hidden}>opis</div>
Ta linia jest tutaj chyba przez przypadek ;) psuje trochę widok bo pod każdym boxem pojawia się napis "opis"

2021-05-30 21:17 UTC, justinaz90 commented on src/components/views/ProductList/ProductList.js
> +                          setShowGrid(false);
Nie jestem pewna, czy to należało do wymagań tego taska, ale dobrze by było gdyby aktywna opcja widoku (grid / list) zmieniała kolor na czarny, tak jak na wizualizacji

2021-05-30 21:24 UTC, justinaz90 commented on src/components/views/ProductList/ProductList.js
> +                  {showList && (
Tak jak napisałaś w komentarzu - widok listy odbiega od wizualizacji, dodatkowo ProductBox'y całkiem się rozjechały i nachodzą na siebie. Podobny efekt do tego z wizualizacji mamy na Product page (tyle że na ten moment nie jest on pobierany ze stanu aplikacji), więc można by wzorować się na jego układzie

2021-05-30 21:27 UTC, justinaz90 requested changes
Jest kilka elementów, które warto by było poprawić, szczególnie widok listy sporo odbiega od wizualizacji. Nie jest to łatwy task, widać, że kosztował Cię już i tak sporo pracy :)

2021-05-30 22:17 UTC, BarbaraPakula commented
Uwagi wyglądają jakby były do pierwsze wersji . Git pull powinno załatwić sprawe

Wiadomość napisana przez justinaz90 ***@***.***> w dniu 30.05.2021, o godz. 23:27:

﻿

@justinaz90 requested changes on this pull request.

Jest kilka elementów, które warto by było poprawić, szczególnie widok listy sporo odbiega od wizualizacji. Nie jest to łatwy task, widać, że kosztował Cię już i tak sporo pracy :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/odevpl/wdp-2105-01/pull/79#pullrequestreview-671865706>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AR7T7MN56YXOR2KGZ223H2DTQKUTZANCNFSM45YQVJRQ>.

2021-05-30 22:26 UTC, BarbaraPakula commented on src/components/views/ProductList/ProductList.js
> +                              <div className={styles.grid_hidden}>opis</div>
to prawda poprawiam

2021-05-30 22:30 UTC, BarbaraPakula commented
Odwołuje źle popatrzyłam
Pozdrawiam Basia

Wiadomość napisana przez Barbara Pakuła ***@***.***> w dniu 31.05.2021, o godz. 00:17:

﻿

Uwagi wyglądają jakby były do pierwsze wersji . Git pull powinno załatwić sprawe

Wiadomość napisana przez justinaz90 ***@***.***> w dniu 30.05.2021, o godz. 23:27:

﻿

@justinaz90 requested changes on this pull request.

Jest kilka elementów, które warto by było poprawić, szczególnie widok listy sporo odbiega od wizualizacji. Nie jest to łatwy task, widać, że kosztował Cię już i tak sporo pracy :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/odevpl/wdp-2105-01/pull/79#pullrequestreview-671865706>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AR7T7MN56YXOR2KGZ223H2DTQKUTZANCNFSM45YQVJRQ>.

2021-05-31 02:29 UTC, BarbaraPakula commented on src/components/views/ProductList/ProductList.js
> +                  {showList && (
Teraz powinno być dużo lepiej i bliżej wizualizacji. Mam nadzieję, że się spodoba

2021-05-31 02:31 UTC, BarbaraPakula commented on src/components/views/ProductList/ProductList.js
> +                  {showList && (
Natchnęłaś mnie i Teraz powinno być lepiej. Zrobiłam nowy komponent. I jesteśmy bliżej oryginału

2021-05-31 07:58 UTC, justinaz90 approved these changes

2021-05-31 08:01 UTC, justinaz90 commented
Wow! No super! :) 👌  Ale nie trzeba było zarywać nocki!! 🙈

2021-05-31 11:38 UTC, merged

2021-05-31 11:39 UTC, odevpl commented
Szacun! :)

2021-05-31 16:49 UTC, BarbaraPakula commented
Mój pierwszy szacun w tej branży. Zapamiętam na długo. Dziękuję.

Pozdrawiam Basia

Wiadomość napisana przez odevpl ***@***.***> w dniu 31.05.2021, o godz. 13:39:

﻿

Szacun! :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/odevpl/wdp-2105-01/pull/79#issuecomment-851430262>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AR7T7MKGKDWIT66SWDFOUWTTQNYOVANCNFSM45YQVJRQ>.